// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Od1GYajNOlMQkXa704yT7Sr9QXVN_YA',
    appId: '1:624208120378:web:2d5a6966ada51501a44303',
    messagingSenderId: '624208120378',
    projectId: 'eve-echoes-tool-5474b',
    authDomain: 'eve-echoes-tool-5474b.firebaseapp.com',
    databaseURL: 'https://eve-echoes-tool-5474b.firebaseio.com',
    storageBucket: 'eve-echoes-tool-5474b.appspot.com',
    measurementId: 'G-JCVC1YXC8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYmQIKg-HPBP18c10vLdM-75d4TDxXWds',
    appId: '1:624208120378:android:d924948f6c316633a44303',
    messagingSenderId: '624208120378',
    projectId: 'eve-echoes-tool-5474b',
    databaseURL: 'https://eve-echoes-tool-5474b.firebaseio.com',
    storageBucket: 'eve-echoes-tool-5474b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgnj66us9cLaPHBPcIo3QJYGkWG7xdtlg',
    appId: '1:624208120378:ios:88369e7b63dbd90fa44303',
    messagingSenderId: '624208120378',
    projectId: 'eve-echoes-tool-5474b',
    databaseURL: 'https://eve-echoes-tool-5474b.firebaseio.com',
    storageBucket: 'eve-echoes-tool-5474b.appspot.com',
    iosClientId: '624208120378-lqbrdeapb422iop6fqd7pn68bhs51do8.apps.googleusercontent.com',
    iosBundleId: 'com.sillykat.eve.sweet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgnj66us9cLaPHBPcIo3QJYGkWG7xdtlg',
    appId: '1:624208120378:ios:88369e7b63dbd90fa44303',
    messagingSenderId: '624208120378',
    projectId: 'eve-echoes-tool-5474b',
    databaseURL: 'https://eve-echoes-tool-5474b.firebaseio.com',
    storageBucket: 'eve-echoes-tool-5474b.appspot.com',
    iosClientId: '624208120378-lqbrdeapb422iop6fqd7pn68bhs51do8.apps.googleusercontent.com',
    iosBundleId: 'com.sillykat.eve.sweet',
  );
}
