// Flutter icons SweetIcons
// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
import 'package:flutter/widgets.dart';

class SweetIcons {
  SweetIcons._();

  static const _kFontFam = 'SweetIcons';
  static const String? _kFontPkg = null;

  static const IconData implant = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitting = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
