# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

screenshots_path './fastlane/metadata/ios/screenshots'
metadata_path './fastlane/metadata/ios/details'